# Generated by Django 3.1.7 on 2021-06-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0002_blogmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogModel',
            new_name='BowlingModel',
        ),
    ]
