# Generated by Django 3.1.7 on 2021-06-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0005_membermodel_member_set_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membermodel',
            old_name='member_set_game',
            new_name='game_set_member',
        ),
    ]
