# Generated by Django 3.1.7 on 2021-06-09 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0009_gamemodel_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='use_date',
        ),
    ]
