# Generated by Django 3.1.7 on 2021-06-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0010_remove_money_use_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money',
            old_name='cost',
            new_name='raund',
        ),
        migrations.RemoveField(
            model_name='money',
            name='detail',
        ),
        migrations.AddField(
            model_name='money',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
