# Generated by Django 3.1.7 on 2021-06-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0011_auto_20210609_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='member',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
