# Generated by Django 3.1.7 on 2021-06-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0013_auto_20210609_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='membername',
        ),
    ]
