# Generated by Django 3.1.7 on 2021-06-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0014_remove_money_membername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membermodel',
            name='type_name',
        ),
    ]
