# Generated by Django 3.1.7 on 2021-06-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0015_remove_membermodel_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='ave',
            field=models.IntegerField(default=0),
        ),
    ]
