# Generated by Django 3.1.7 on 2021-06-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0017_auto_20210609_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='max',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='money',
            name='min',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
