# Generated by Django 3.1.7 on 2021-06-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0019_auto_20210610_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='ave',
            field=models.IntegerField(default=0),
        ),
    ]
