# Generated by Django 3.1.7 on 2021-06-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0020_auto_20210610_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='ave',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
