# Generated by Django 3.1.7 on 2021-06-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0023_auto_20210610_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='money',
            name='team_choice',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='membername',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='membername',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='money',
            name='member',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
