# Generated by Django 3.1.7 on 2021-06-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0024_auto_20210610_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCalculusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default=0, max_length=3)),
                ('sum_total', models.IntegerField(default=0)),
                ('point_alloc', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamemodel',
            name='game_set_member',
        ),
    ]
