# Generated by Django 3.1.7 on 2021-06-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0025_auto_20210610_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcalculusmodel',
            name='raund',
            field=models.IntegerField(default=0),
        ),
    ]
