# Generated by Django 3.1.7 on 2021-06-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0026_teamcalculusmodel_raund'),
    ]

    operations = [
        migrations.AddField(
            model_name='money',
            name='pin',
            field=models.IntegerField(default=0),
        ),
    ]
