# Generated by Django 3.1.7 on 2021-06-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0032_eachgamedatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eachgamedatamodel',
            name='datetime',
            field=models.CharField(max_length=20),
        ),
    ]
