# Generated by Django 3.1.7 on 2021-06-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0034_auto_20210618_1332'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Money',
            new_name='CoreModel',
        ),
    ]
