# Generated by Django 3.1.7 on 2021-06-18 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0035_auto_20210618_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coremodel',
            name='point_alloc',
        ),
    ]
