# Generated by Django 3.1.7 on 2021-06-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0036_remove_coremodel_point_alloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='coremodel',
            name='handicap',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='coremodel',
            name='score_h',
            field=models.IntegerField(default=0),
        ),
    ]
