# Generated by Django 3.1.7 on 2021-06-20 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0037_auto_20210619_2040'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BowlingModel',
        ),
    ]
