# Generated by Django 3.1.7 on 2021-06-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bowlingapp', '0038_delete_bowlingmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coremodel',
            name='user_set',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='eachgamedatamodel',
            name='user_set',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='user_set',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='user_set',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='teamcalculusmodel',
            name='user_set',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
